export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const HANDLE_AUTHENTICATION = "HANDLE_AUTHENTICATION";
export const AUTHENTICATE_CHECKED = "AUTHENTICATE_CHECKED";
export const TRIGGER_DRAWER = "TRIGGER_DRAWER";
