export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const HANDLE_AUTHENTICATION = "HANDLE_AUTHENTICATION";
export const AUTHENTICATE_CHECKED = "AUTHENTICATE_CHECKED";
export const TRIGGER_DRAWER = "TRIGGER_DRAWER";
export const ADD_QUERY = "ADD_QUERY";
export const CHANGE_SELCETED_QUERY = "CHANGE_SELCETED_QUERY";
export const GET_SELECTED_QUERY_DATA = "GET_SELECTED_QUERY_DATA";
export const CHANGE_SNACKBAR_STATUS = "CHANGE_SNACKBAR_STATUS";
export const SELECT_QUERY_MENU = "SELECT_QUERY_MENU";
export const SELECT_QUERY_DASHBOARD_LIST_ITEM =
  "SELECT_QUERY_DASHBOARD_LIST_ITEM";
export const SELECT_EMOTION = "SELECT_EMOTION";
export const SELECT_GROUP = "SELECT_GROUP";
export const SELECT_PAGE = "SELECT_PAGE";
export const SELECT_ANALYSIS_TYPE = "SELECT_ANALYSIS_TYPE";
export const CHANGE_ANALYSIS_STATUS = "CHANGE_ANALYSIS_STATUS";
export const SELECT_QUERIES_TYPE = "SELECT_QUERIES_TYPE";
export const CHANGE_QUERY_STATUS = "CHANGE_QUERY_STATUS";
export const SELECT_QUERY = "SELECT_QUERY";
export const SELECT_KEYWORD = "SELECT_KEYWORD";
export const BACK_TO_QUERIES = "BACK_TO_QUERIES";
export const CANCEL_CREATE = "CANCEL_CREATE";
/* *** */
export const EDITABLE_QUERY = "EDITABLE_QUERY";
export const EDITABLE_PROJECT = "EDITABLE_PROJECT";
export const EDITABLE_TRAFFIC_ANALYSIS = "EDITABLE_TRAFFIC_ANALYSIS";
/* *** */
export const GO_TO_ADD_QUERY = "GO_TO_ADD_QUERY";
export const CHANGE_ADD_QUERY = "CHANGE_ADD_QUERY";
export const CREATE_QUERY = "CREATE_QUERY";
export const DELETE_QUERY = "DELETE_QUERY";
export const CHANGE_EDITABLE_QUERY = "CHANGE_EDITABLE_QUERY";
export const EDIT_QUERY = "EDIT_QUERY";
/* *** */
export const GO_TO_ADD_TRAFFIC_ANALYSIS = "GO_TO_ADD_TRAFFIC_ANALYSIS";
export const CHANGE_ADD_TRAFFIC_ANALYSIS = "CHANGE_ADD_TRAFFIC_ANALYSIS";
export const CREATE_TRAFFIC_ANALYSIS = "CREATE_TRAFFIC_ANALYSIS";
export const DELETE_TRAFFIC_ANALYSIS = "DELETE_TRAFFIC_ANALYSIS";
export const CHANGE_EDITABLE_TRAFFIC_ANALYSIS =
  "CHANGE_EDITABLE_TRAFFIC_ANALYSIS";
export const EDIT_TRAFFIC_ANALYSIS = "EDIT_TRAFFIC_ANALYSIS";
/* *** */
export const GO_TO_ADD_PROJECT = "GO_TO_ADD_PROJECT";
export const CHANGE_ADD_PROJECT = "CHANGE_ADD_PROJECT";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const CHANGE_EDITABLE_PROJECT = "CHANGE_EDITABLE_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
/* *** */
export const CHANGE_BAG_ITEM_STATUS = "CHANGE_BAG_ITEM_STATUS";
export const CHECK_ALL_BAG_ITEM_STATUS = "CHECK_ALL_BAG_ITEM_STATUS";
export const CHANGE_GLOBAL_VAR = "CHANGE_GLOBAL_VAR";
export const CHANGE_COME_FROM = "CHANGE_COME_FROM";
